### ISSUE TITLE
Upload 2.2.0 to maven central

### ISSUE THREAD

**Issue by kno10** [jeffhain/jafama#2]
For maven users, the latest version is still 2.1.0:

https://mvnrepository.com/artifact/net.jafama/jafama

**Comment by jeffhain** [comment]
Hello.
The new version, 2.3, is now on central:
https://mvnrepository.com/artifact/net.jafama/jafama/2.3.0

Sorry for being so lazy for so long, but as I said for another pull request, I'm mostly focused on some other big project ATM, and I was missing will for context switching, especially because I had to sort out my messy notes about what I did to upload to central the first time.
There was also nothing very useful in 2.2, just a few cornercase methods and lazy tables initialization (which can have its drawbacks, which is why I added initTables() method along with it).
